# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b020747d8f308d6c44348bb4f53a3d1a72e11faaaddbd305601b53b49333b0593aba6fd0c64f527a6ac8738e6f4d27ebbe142aefd9a867a930c93ca0e953d462

test:
  secret_key_base: 8e52b770a10088a09b72832c4c8d0172028888ec306665deb84114309c755de2c8858d0122d0c542ca5e3ae91a349a1ea0c7b9d005609f7c84ef8e924310443c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
